### ISSUE TITLE
Can't run TAGE

### ISSUE THREAD

**Issue by TsangKwunHei** [siavashzk/BranchNet#14]
Thank you for making BranchNet, I am really excited to try it.
I have a custom branch trace that I want to run. 
After the hours of debugging, I finally fine-tuned my trace format such that run.out does not show errors like for incorrect BR type and other formatting issues. 
Yet, there is nothing on the csv files... it seems tage didn't run after initialisation?  I'm sure the file path and the formatting have no problem, because I've spent hours fixing it and those problems are fixed now.

Result on .csv : 
Branch PC,Accuracy,Mispredictions,Correct Predictions,Total,dir_t_pred_t,dir_t_pred_nt,dir_nt_pred_t,dir_nt_pred_nt
aggregate,nan%,0,0,0,0,0,0,0

Could it be because of my benchmarks.yaml has only one file specified? It is because I used my own trace file, which is everything is included in that file, 
```
planets:
  inputs:
  - name: train1
    simpoints:
    - id: 0
      path: /Users/kwunhei/prediction/custom/BranchNet-master
      type: pinball
      weight: 1
```
